<div class="success">
    <p><?= /* @escapeNotVerified */ __('We have sent an email​<br/>with the link to reset your password.') ?></p>
    <div class="actions-toolbar">
        <div class="primary"><a href="<?= $block->escapeUrl($block->getUrl('*/*')) ?>" class="action button login primary"><span><?= $block->escapeHtml(__('Login')) ?></span></a></div>
        <div class="secondary">
            <?= $block->escapeHtml(__('Didn’t receive the link?')) ?>
            <a class="remind" href="<?= $block->escapeUrl($block->getUrl('customer/account/forgotpassword')) ?>"><span><?= $block->escapeHtml(__('Resend')) ?></span></a>
        </div>
    </div>
</div>
