<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/* @var $block \Magento\ProductAlert\Block\Product\View */
/** @var Magento\Framework\Escaper $escaper */
/** @var \Eguana\NotifyMe\ViewModel\Notification $viewModel */
$viewModel = $block->getData('view_model');
$createUrl = $block->createUrl();
?>
<div class="notify-me-popup primary action <?= $block->getHtmlClass() ?>">
    <a href="#"
       title="<?= $escaper->escapeHtml(__($block->getSignupLabel())) ?>" class="action alert">
        <?= $escaper->escapeHtml(__($block->getSignupLabel())) ?>
    </a>
</div>

<div class="notify-me-modal">
    <form class="form notification-form" id="notification-form" method="post" data-mage-init='{"validation": {}}'>
        <input type="hidden" name="product_id" id="product_id"  value="<?= $escaper->escapeHtmlAttr($block->getCurrentProduct()->getId()) ?>">
        <fieldset class="fieldset">
            <div class="field note"><?= $block->escapeHtml(__('We will notify you when this product will be available for sale.')) ?></div>
            <div class="field customer-email required">
                <label class="label" for="customer_email"><span><?= $escaper->escapeHtml(__('Email')); ?></span></label>
                <div class="control">
                    <input type="text" data-validate='{"required":true, "validate-email": true}' placeholder="<?= $block->escapeHtmlAttr(__('Eguana@gmail.com')) ?>" name="customer_email" id="customer_email" value="" class="input-text" >
                </div>
            </div>
            <div class="field customer-mobile required">
                <label class="label" for="customer_mobile"><span><?= $escaper->escapeHtml(__('Mobile')); ?></span></label>
                <div class="control">
                    <input type="text" data-validate='{"required":true, "validate-number": true, "minlength":10}' placeholder="<?= $block->escapeHtmlAttr(__('010-1234-5678')) ?>" name="customer_mobile" id="customer_mobile" value="" class="input-text" />
                </div>
            </div>
            <div class="field choice required">
                <input type="checkbox" name="privacy_policy" id="privacy-policy" data-role="privacy-policy" value="1" data-validate="{required:true}" class="checkbox required-entry"/>
                <label for="privacy-policy"
                       class="label"><span><?= $block->escapeHtml(__('I have read and agree to the privacy policy.<span>(Required)</span>'),['span'])?></span><a title="<?= $block->escapeHtmlAttr(__('Go to Privacy Policy Page')) ?>" href="<?= $block->getUrl('privacy-policy')?>"><?= $block->escapeHtml(__('Read all')) ?></a></label>
            </div>
        </fieldset>
    </form>
</div>

<script type="text/x-magento-init">
   {
       "*": {
           "notifyMe": {
                "url": "<?= $viewModel->getNotificationSubmitUrl(); ?>",
                "product_id": "<?= $escaper->escapeHtmlAttr($block->getCurrentProduct()->getId()); ?>",
                "alert_class": ".alert"
           }
       }
   }
</script>

