<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Framework\Escaper $escaper */

?>
<div class="notify-me-modal" style="display: none">
    <form class="form notification-form" id="notification-form" method="post" data-mage-init='{"validation": {}}'>
        <input type="hidden" name="product_id" id="product_id" value="">
        <fieldset class="fieldset">
            <div class="field note"><?= $block->escapeHtml(__('We will notify you when this product will be available for sale.')) ?></div>
            <div class="field customer-email required">
                <label class="label" for="customer_email"><span><?= $escaper->escapeHtml(__('Email')); ?></span></label>
                <div class="control">
                    <input type="text" data-validate='{"required":true, "validate-email": true}' placeholder="<?= $block->escapeHtmlAttr(__('Eguana@gmail.com')) ?>" name="customer_email" id="customer_email" value="" class="input-text" >
                </div>
            </div>
            <div class="field customer-mobile required">
                <label class="label" for="customer_mobile"><span><?= $escaper->escapeHtml(__('Mobile')); ?></span></label>
                <div class="control">
                    <input type="text" data-validate='{"required":true, "validate-number": true, "minlength":10}' placeholder="<?= $block->escapeHtmlAttr(__('010-1234-5678')) ?>" name="customer_mobile" id="customer_mobile" value="" class="input-text" />
                </div>
            </div>
            <div class="field choice required">
                <input type="checkbox" name="privacy_policy" id="privacy-policy" data-role="privacy-policy" value="1" data-validate="{required:true}" class="checkbox required-entry"/>
                <label for="privacy-policy"
                       class="label"><span><?= $block->escapeHtml(__('I have read and agree to the privacy policy.<span>(Required)</span>'),['span'])?></span><a title="<?= $block->escapeHtmlAttr(__('Go to Privacy Policy Page')) ?>" href="<?= $block->getUrl('privacy-policy')?>"><?= $block->escapeHtml(__('Read all')) ?></a></label>
            </div>
        </fieldset>
    </form>
</div>
