<div class="success">
    <p><?= /* @escapeNotVerified */ __('We appreciate you reaching out to us,<br/>and we will get back to you as soon as possible. Talk to you soon!') ?></p>
    <div class="actions-toolbar">
        <div class="primary"><a href="<?= $block->escapeUrl($block->getUrl()); ?>" class="action button login primary"><span><?= $block->escapeHtml(__('Back to Home')) ?></span></a></div>
    </div>
</div>
